module.exports = {
  customerExist: 'Klient istnieje w bazie danych, {nip}.',
  customerNoName: 'Nie można utworzyć klienta brak jego nazwy!',
  customerInvalidNIP: 'Nie można utworzyć klineta, zły NIP',
  customerCanNotAdd: 'Nie można dodać klienta dla tego obiektu, klient już istnieje!',
  customerCreate: 'Tworzenie klienta {email}',
  customerCreated: 'Stworzono klienta: {symbol}',
  customerRemove: 'Usuwanie klienta {email}',
  customerRemoved: 'Usunięto klienta {email}',
  orderitemNoSymbol: 'Element zamówienia {name}: nie posiada symbolu!',
  productNoSymbol: 'Towar - nie posiada symbolu!',
  productNoExist: 'Symbol: {symbol} nie istnieje w systemie!',
  orderStartElement: '<<< Przetwarzanie zamówienia {current}/{all}. >>>',
  orderStart: 'Przetwarzanie zamówienia od {email}',
  orderNoProducts: 'Brak produktów w zamówieniu!',
  orderCreated: 'Zamówienie stworzone pomyślnie',
  statusNotExist: 'Cannot find status: {statusToFind}',
  orderInvalidPaymentAmmount: 'Kwota zapłaty nie zgadza się z wartością zamówienia.',
};
