module.exports = ({
  order_id: orderId,
  user_comments: userComments,
  admin_comments: adminComments,
  delivery_method: deliveryMethod,
  delivery_point_name: deliveryPointName,
  delivery_price: deliveryPrice,
  email,
  invoice_address: invoiceAddress,
  invoice_city: invoiceCity,
  invoice_company: invoiceCompany,
  invoice_country: invoiceCountry,
  invoice_fullname: invoiceFullname,
  invoice_nip: invoiceNip,
  invoice_postcode: invoicePostcode,
  payment_done: payment,
  phone,
  products,
  user_comments: comments,
  user_login: login,
}) => ({
  orderId,
  deliveryPrice,
  deliveryMethod,
  deliveryPointName,
  payment,
  comments: {
    userComments,
    adminComments,
  },
  customer: {
    comments,
    email,
    invoiceAddress,
    invoiceCity,
    invoiceCompany,
    invoiceCountry,
    invoiceFullname,
    invoiceNip,
    invoicePostcode,
    login,
    phone,
  },
  products: products.map(({
    name, sku: symbol, price_brutto: price, quantity,
  }) => ({
    name,
    price,
    quantity,
    symbol,
  })),
});
